name: Build LevelLife APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build APK with buildozer
        uses: kivy/kivy-ci/buildozer-action@master
        with:
          command: buildozer android debug
          buildozer_version: stable
